### ISSUE TITLE
Mix crashing few seconds after opening a project

### ISSUE THREAD

**Issue by zikilemini** [ethereum/mix#305] opened 2016-04-22 19:55 UTC
Hello i was working on mix and one day it just stopped to work, i tried to get the last version , to delete all my files, nothing worked.

When i launch mix, it work like one second before crashing with this logs : 
`
WARNING: This project is using the experimental QML API extensions for QtWebEngine and is therefore tied to a specific QtWebEngine release.
WARNING: The experimental API will change from version to version, or even be removed. You have been warned!

QtWebEngineProcess not found at location E:/Ethereum/Mist/Ethereumb/bin\QtWebEngineProcess.exe. Trying fallback path...
Layout must be attached to Item elements
Layout must be attached to Item elements
qml: [{"id":0,"jsonrpc":"2.0","method":"eth_accounts","params":[]}]
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
qrc:/qml/DebugInfoList.qml:124:3: QML Loader: Binding loop detected for property "height"
qrc:/qml/DebugInfoList.qml:124:3: QML Loader: Binding loop detected for property "height"
qrc:/qml/DebugInfoList.qml:124:3: QML Loader: Binding loop detected for property "height"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
qrc:/QtQuick/Controls/ScrollView.qml:232:9: QML Binding: Binding loop detected for property "value"
qrc:/QtQuick/Controls/ScrollView.qml:225:9: QML Binding: Binding loop detected for property "value"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
  i  21:48:22.345|main  Killing blockchain & extras database (WithExisting::Kill).
  i  21:48:22.374|main  Killing state database (WithExisting::Kill).
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
qml: [{"id":0,"jsonrpc":"2.0","method":"eth_accounts","params":[]}]
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
  i  21:48:22.409|main  Killing blockchain & extras database (WithExisting::Kill).
  i  21:48:22.436|main  Killing state database (WithExisting::Kill).
  i  21:48:22.466|main  Killing blockchain & extras database (WithExisting::Kill).
  i  21:48:22.493|main  Killing state database (WithExisting::Kill).
qml: Closing project
qml: Loading project at file:///E:/Ethereum/EthTest/Store
qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
qrc:/QtQuick/Controls/TextArea.qml:728:24: Unable to assign [undefined] to QColor
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:72:42: Unable to assign TextArea_QMLTYPE_120 to TextField_QMLTYPE_49
qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
qml: [{"id":0,"jsonrpc":"2.0","result":["0xef49d7bf6cd9a01fa487f94d4e79a6be31f89a34","0x061e9edd85b8672f628a3567bc888de3e0c2cae9","0xe022cd6bf97b1d4319de299d0a654162040112c2"]}]

qml: [{"id":"0","jsonrpc":"2.0","method":"eth_getBalance","params":["0xef49d7bf6cd9a01fa487f94d4e79a6be31f89a34","latest"]},{"id":"1","jsonrpc":"2.0","method":"eth_getBalance","params":["0x061e9edd85b
8672f628a3567bc888de3e0c2cae9","latest"]},{"id":"2","jsonrpc":"2.0","method":"eth_getBalance","params":["0xe022cd6bf97b1d4319de299d0a654162040112c2","latest"]}]
qml: [{"id":1,"jsonrpc":"2.0","result":"0x4a817c800"}]

qml: [{"id":1,"jsonrpc":"2.0","result":"0x4a817c800"}]

qml: [{"id":1,"jsonrpc":"2.0","result":"0x4a817c800"}]

qml: [{"id":0,"jsonrpc":"2.0","result":["0xef49d7bf6cd9a01fa487f94d4e79a6be31f89a34","0x061e9edd85b8672f628a3567bc888de3e0c2cae9","0xe022cd6bf97b1d4319de299d0a654162040112c2"]}]

qml: [{"id":"0","jsonrpc":"2.0","method":"eth_getBalance","params":["0xef49d7bf6cd9a01fa487f94d4e79a6be31f89a34","latest"]},{"id":"1","jsonrpc":"2.0","method":"eth_getBalance","params":["0x061e9edd85b
8672f628a3567bc888de3e0c2cae9","latest"]},{"id":"2","jsonrpc":"2.0","method":"eth_getBalance","params":["0xe022cd6bf97b1d4319de299d0a654162040112c2","latest"]}]
qml: [{"id":"0","jsonrpc":"2.0","result":"0x97d92a04fe149cf5"},{"id":"1","jsonrpc":"2.0","result":"0x03b363eba41aaaac"},{"id":"2","jsonrpc":"2.0","result":"0x0caefaee6a154adc"}]

qml: [{"id":"0","jsonrpc":"2.0","result":"0x97d92a04fe149cf5"},{"id":"1","jsonrpc":"2.0","result":"0x03b363eba41aaaac"},{"id":"2","jsonrpc":"2.0","result":"0x0caefaee6a154adc"}]

[0x7FEEC86AAA0] ANOMALY: meaningless REX prefix used
[0x7FEEC8548C0] ANOMALY: meaningless REX prefix used
[0x7FEE89354A0] ANOMALY: meaningless REX prefix used
[0x7FEE8192FF0] ANOMALY: meaningless REX prefix used
[0x7FEE81931B0] ANOMALY: meaningless REX prefix used
[0x7FEE8193300] ANOMALY: meaningless REX prefix used
[0x7FEE81937E0] ANOMALY: meaningless REX prefix used
[0x7FEE8193820] ANOMALY: meaningless REX prefix used
qml: Closing project
qml: Creating project 1 at file://C:/Users/rÚmi
qml: Closing project
qml: Loading project at file://C:/Users/rÚmi/1
  i  21:49:22.984|main  Killing blockchain & extras database (WithExisting::Kill).
  i  21:49:23.015|main  Killing state database (WithExisting::Kill).
Waiting for current execution to complete
  i  21:49:24.636|<unknown>  Decreasing DB node ref count below zero with no DB node. Probably have a corrupt Trie. #84acdce9ÔÇª
  i  21:49:24.643|<unknown>  Decreasing DB node ref count below zero with no DB node. Probably have a corrupt Trie. #a71b164eÔÇª
`

I am on windows 7

**Comment by bobsummerwill** [comment] 2016-06-10 05:01
Closed as dupe of "The Heisenbug" - https://github.com/ethereum/webthree-umbrella/issues/565.   We can reopen if we later find there is anything unique here.

**Closed as completed by bobsummerwill** 2016-06-10 05:01 UTC
Labels: bug
