### ISSUE TITLE
crash on start when using prebuild binaries (EL CAPITAN)

### ISSUE THREAD

**Issue by LianaHus** [ethereum/mix#265] opened 2016-02-25 11:20 UTC
moved from cpp-ethereum repo. https://github.com/ethereum/cpp-ethereum/issues/2996

**Comment by fzzr-** [comment] 2016-03-05 02:50
Have the same issue :(

**Comment by bobsummerwill** [comment] 2016-06-10 05:01
Closed as dupe of "The Heisenbug" - https://github.com/ethereum/webthree-umbrella/issues/565.   We can reopen if we later find there is anything unique here.

**Closed as completed by bobsummerwill** 2016-06-10 05:01 UTC
Labels: bug
