### ISSUE TITLE
Mix crashes on startup (El Capitan)

### ISSUE THREAD

**Issue by mati21** [ethereum/mix#301] opened 2016-04-19 17:45 UTC
I've installed latest (1.2.4) cpp-ethereum using homebrew.

Mix-ide crashes on startup with a "Mix-ide quit unexpectedly" message.

I've tried reinstalling but no luck.

**Comment by bobsummerwill** [comment] 2016-04-19 18:11
Thanks for the report, @mati21.

CC @yann300, @LianaHus.

Sorry to hear that.   We're had various stability issues with Mix.

In the meantime, you might have more success with building from source?   Perhaps you could give that a go for now?

http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/osx.html

**Comment by mati21** [comment] 2016-04-19 19:01
Great! Thanks @bobsummerwill. It works when building from source.

Do you reckon I should report it to the homebrew package repo? I have no idea what caused that issue.

**Comment by bobsummerwill** [comment] 2016-04-19 19:06
Excellent.

No - please just leave this with us, and we can triage.     The Homebrew repo is our own "tap", so the issue might be with our own binaries, or with some nasty interaction between prebuilt binaries elsewhere.

Takes time to work through this stuff ... sadly!

**Comment by bobsummerwill** [comment] 2016-06-10 05:01
Closed as dupe of "The Heisenbug" - https://github.com/ethereum/webthree-umbrella/issues/565.   We can reopen if we later find there is anything unique here.

**Closed as completed by bobsummerwill** 2016-06-10 05:01 UTC
Labels: bug
